### ISSUE TITLE
Request for Checkpoint Upload to Google Drive or OneDrive.

### ISSUE THREAD

**Issue by MinGiSa** [Windaway/DCAM#3]
Hello,

I am trying to run the code, but I can't access Baidu to download the checkpoint. 

Could you upload the checkpoint to Google Drive or OneDrive instead?

**Comment by Windaway** [comment]
Mega url:
https://mega.nz/folder/KFZwjZSA#Uh2kXT2XjpaOG_nhMDjCwA
