### ISSUE TITLE
Are you willing to share the training code?

### ISSUE THREAD

**Issue by MinGiSa** [Windaway/DCAM#4]
Thanks to the new cloud service you introduced,
I was able to download the pretrained model and successfully perform inference.
Thank you very much.
By the way, are you considering sharing the training code?
I'm planning to train it on a custom dataset.

**Comment by Windaway** [comment]
I will organize and release the code for automatting when I have time. Or you can refer to the training code at https://github.com/QLYoo/AEMatter.
